telegram_token: "8174600040:AAG3gZ7SepHl0EzLRwq08_0kpphPgEZRBYU"
telegram_chat_id: "fastangel_bot"
dex_apis:
  - name: Uniswap
    url: "https://api.uniswap.org/v1/prices"
  - name: Sushiswap
    url: "https://api.sushiswap.org/v1/prices"
threshold_profit: 0.5
